SECRET_KEY = 'YOUR-SECRET-KEY'
POSTGRES_USER_PASSWORD = 'POSTGRES-USER-PASSWORD' # Пароль от аккаунта postgres
DATABASE_USER = 'USERNAME'
DATABASE_USER_PASSWORD = 'PASSWORD'
DATABASE_NAME = 'database_db'