"""create borrowed_books table

Revision ID: 2ec0d5078b0c
Revises: e6da0955bd14
Create Date: 2025-06-15 13:18:27.037228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec0d5078b0c'
down_revision: Union[str, None] = 'e6da0955bd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('borrowed_books_book_id_key'), 'borrowed_books', type_='unique')
    op.drop_constraint(op.f('borrowed_books_reader_id_key'), 'borrowed_books', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('borrowed_books_reader_id_key'), 'borrowed_books', ['reader_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('borrowed_books_book_id_key'), 'borrowed_books', ['book_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
