"""create librarians table

Revision ID: 3ca370dbc812
Revises: 9f091205cc9e
Create Date: 2025-06-14 13:00:51.979060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca370dbc812'
down_revision: Union[str, None] = '9f091205cc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'librarians', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'librarians', type_='unique')
    # ### end Alembic commands ###
