"""create librarians table

Revision ID: 440c216784f7
Revises: 3ca370dbc812
Create Date: 2025-06-14 13:27:24.661002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440c216784f7'
down_revision: Union[str, None] = '3ca370dbc812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('librarians', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('librarians', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('librarians', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('librarians', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
